# Generated by Django 4.2.6 on 2023-10-27 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b1', '0002_user_application_category_realization_delete_advuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agreement',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персоональных данных'),
        ),
        migrations.AlterField(
            model_name='user',
            name='applications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='b1.application', verbose_name='Заявки'),
        ),
    ]
