# Generated by Django 4.2.6 on 2023-11-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b1', '0003_alter_user_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='New', max_length=254, verbose_name='Статус'),
        ),
    ]
