# Generated by Django 4.2.6 on 2023-10-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b1', '0004_alter_application_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='realization',
            name='name',
            field=models.CharField(max_length=254, null=True, verbose_name='Описание'),
        ),
    ]
