# Generated by Django 4.2.6 on 2023-10-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b1', '0005_realization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realization',
            name='name',
            field=models.CharField(max_length=254, null=True, verbose_name='Название'),
        ),
    ]
