# Generated by Django 4.2.6 on 2023-10-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b1', '0006_alter_realization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='realization',
            name='date_execution',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_execution',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Имя заявки'),
        ),
        migrations.AlterField(
            model_name='realization',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Название'),
        ),
    ]
