# Generated by Django 4.2.6 on 2023-10-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b1', '0007_realization_date_execution_user_date_execution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_execution',
        ),
        migrations.AddField(
            model_name='application',
            name='date_execution',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
