# Generated by Django 4.2.6 on 2023-10-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b1', '0008_remove_user_date_execution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='date_execution',
            new_name='date_creation',
        ),
    ]
